Fail mvn process if there is any test errors
wildfly/ejb-client-testsuite pull request #9
Opened 2024-02-14 09:53 UTC by marekkopecky

I believe that such settings (`maven.test.failure.ignore`) should be configured in CI configuration (by `-Dmaven.test.failure.ignore=true` property) if necessary. But should not be configured directly in pom files.

My understanding is that `multinode/pom-wildfly-client.xml` is not used in upstream CI. But if pom.xml changes would cause any troubles for upstream CI, I can update QE CI and override this value there, but I believe that clearer way is to clear it from pom files directly.

2024-02-14 09:53 UTC, marekkopecky commented
@tadamski  can you please check this PR?

2024-02-14 11:24 UTC, jbliznak commented
more instances - we should remove all of them, right?
https://github.com/search?q=repo%3Awildfly%2Fejb-client-testsuite%20maven.test.failure.ignore&type=code

2024-02-14 11:27 UTC, tadamski requested changes
@marekkopecky OK. Could you also remove other one that @jbliznak mentioned and I will merge.

2024-02-14 14:02 UTC, marekkopecky commented
Well, last one is in jacoco profile - I believe that there is valid usage of it, because if we run jacoco, we are not interested about the results of tests, but about the test coverage - https://github.com/wildfly/ejb-client-testsuite/blob/1607b49378c9b3855a0c7a77cc6772349e29db9e/basic/pom.xml#L494

Anyway, I don't have strong feeling about it and definitely can remove it. @jbliznak WDYT?

2024-02-15 09:28 UTC, marekkopecky commented
There are some profiles that can be used with jacoco (like `specificModule` that just set EJB configuration), others can't be used with jacoco (eg `debugServer` sets JVM agents for debuging, and second jacoco agent could cause troubles), but I would say that documenting this is low-level info for readmes.

2024-02-16 16:58 UTC, tadamski approved these changes
OK. Merging then.

2024-02-16 16:58 UTC, merged